### ISSUE TITLE
There is no judgment whether it is ipv6, resulting in players being unable to join ipv6 servers.

### ISSUE THREAD

**Issue by xsj284** [Reider745/ZoteCoreLoader#4]
# Position: com.reider745.hooks.PlayerHooks.isAddress
![屏幕截图 2024-02-07 011338](https://github.com/Reider745/ZoteCoreLoader/assets/72089458/c86f907c-4757-4db4-a6ac-bf658cb04c23)
# You can add the following code：
![屏幕截图 2024-02-07 025223](https://github.com/Reider745/ZoteCoreLoader/assets/72089458/68e80901-052b-4e74-9f1c-18946b4e6972)

**Comment by rislaed** [comment]
It was piece of non-refactored code, sorry for inconvenience. We will change authorization method in next indev release.
