### ISSUE TITLE
Inconsistent remark

### ISSUE THREAD

**Issue by Reider745** [Reider745/ZoteCoreLoader#5]
Backport of modular patches.

**Comment by IbremMiner837** [comment]
@Reider745 АПХАХАХВХВ

**Comment by IbremMiner837** [comment]
@IbremMiner837 Тест

**Comment by MaXFeeD** [comment]
> @IbremMiner837 Тест

шо по рукам надавать 🗿

**Comment by IbremMiner837** [comment]
@MaXFeeD Иди вон 🚬

**Comment by IbremMiner837** [comment]
@MaXFeeD Не спамь в чат нам 🗿

**Comment by intbyte-100** [comment]
@IbremMiner837 а типо если ответить на это сообщение в тг, то бот автоматически его на гитхаб отправит?
